### ISSUE TITLE
Cannot startup carpet server since Carpet_19_03_08b

### ISSUE THREAD

**Issue by wegood9** [gnembon/carpetmod112#104]
The Minecraft server that any carpet mod newer than `Release 19_03_08b (including Carpet_19_03_08b)` is applied to will hang up when loading a world. The server will freeze and can't response to server commands unless a forced shutdown signal sent. Both Minecraft version 1.12 and 1.12.2 encounter the same problem. However, Older versions like `Carpet_19_02_17` work without any problems.

The checksums of the original server jars I used to be patched were matched with what Mojang provided, and I completely followed the instruction. I tried running a server in Windows 10 with `Oracle Java 8u241` and Debian with `openjdk 11`, only to come across this problem in both environments. Windows reported an Event 1002 "Application Hang" of javaw.exe and the reason was `Top level window is idle`. Debian didn't provide anything useful.
<details>
<summary>A typical log of minecraft server before freezing looks like this:</summary>
<pre><code>
[23:47:22] [main/ERROR]: Errors with built-in recipes!
[23:47:22] [Server thread/INFO]: Starting minecraft server version 1.12
[23:47:22] [Server thread/INFO]: Loading properties
[23:47:22] [Server console handler/ERROR]: Exception handling console input
java.io.IOException: InvaildHandle
	at java.io.FileInputStream.readBytes(Native Method) ~[?:1.8.0_241]
	at java.io.FileInputStream.read(Unknown Source) ~[?:1.8.0_241]
	at java.io.BufferedInputStream.read1(Unknown Source) ~[?:1.8.0_241]
	at java.io.BufferedInputStream.read(Unknown Source) ~[?:1.8.0_241]
	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source) ~[?:1.8.0_241]
	at sun.nio.cs.StreamDecoder.implRead(Unknown Source) ~[?:1.8.0_241]
	at sun.nio.cs.StreamDecoder.read(Unknown Source) ~[?:1.8.0_241]
	at java.io.InputStreamReader.read(Unknown Source) ~[?:1.8.0_241]
	at java.io.BufferedReader.fill(Unknown Source) ~[?:1.8.0_241]
	at java.io.BufferedReader.readLine(Unknown Source) ~[?:1.8.0_241]
	at java.io.BufferedReader.readLine(Unknown Source) ~[?:1.8.0_241]
	at nx$2.run(DedicatedServer.java:102) [server.1.12.jar:?]
[23:47:22] [Server thread/INFO]: Default game type: CREATIVE
[23:47:22] [Server thread/INFO]: Generating keypair
[23:47:23] [Server thread/INFO]: Starting Minecraft server on *:25565
[23:47:23] [Server thread/INFO]: Using default channel type
[23:47:23] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[23:47:23] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[23:47:23] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[23:47:23] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[23:47:23] [Server thread/INFO]: Preparing level "world"
[23:47:23] [Thread-6/INFO]: [STDERR]: java.io.UncheckedIOException: java.io.EOFException: Unexpected end of ZLIB input stream
[23:47:23] [Thread-6/INFO]: [STDERR]: 	at java.io.BufferedReader$1.hasNext(Unknown Source)
[23:47:23] [Thread-6/INFO]: [STDERR]: 	at java.util.Iterator.forEachRemaining(Unknown Source)
[23:47:23] [Thread-6/INFO]: [STDERR]: 	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
[23:47:23] [Thread-6/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[23:47:23] [Thread-6/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[23:47:23] [Thread-6/INFO]: [STDERR]: 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[23:47:23] [Thread-6/INFO]: [STDERR]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
[23:47:23] [Thread-6/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[23:47:23] [Thread-6/INFO]: [STDERR]: 	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
[23:47:23] [Thread-6/INFO]: [STDERR]: 	at carpet.helpers.StackTraceDeobfuscator.loadNames(StackTraceDeobfuscator.java:264)
[23:47:23] [Thread-6/INFO]: [STDERR]: 	at carpet.helpers.StackTraceDeobfuscator.lambda$loadMappings$1(StackTraceDeobfuscator.java:233)
[23:47:23] [Thread-6/INFO]: [STDERR]: 	at java.lang.Thread.run(Unknown Source)
[23:47:23] [Thread-6/INFO]: [STDERR]: Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
[23:47:23] [Thread-6/INFO]: [STDERR]: 	at java.util.zip.InflaterInputStream.fill(Unknown Source)
[23:47:23] [Thread-6/INFO]: [STDERR]: 	at java.util.zip.InflaterInputStream.read(Unknown Source)
[23:47:23] [Thread-6/INFO]: [STDERR]: 	at java.util.zip.ZipInputStream.read(Unknown Source)
[23:47:23] [Thread-6/INFO]: [STDERR]: 	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
[23:47:23] [Thread-6/INFO]: [STDERR]: 	at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
[23:47:23] [Thread-6/INFO]: [STDERR]: 	at sun.nio.cs.StreamDecoder.read(Unknown Source)
[23:47:23] [Thread-6/INFO]: [STDERR]: 	at java.io.InputStreamReader.read(Unknown Source)
[23:47:23] [Thread-6/INFO]: [STDERR]: 	at java.io.BufferedReader.fill(Unknown Source)
[23:47:23] [Thread-6/INFO]: [STDERR]: 	at java.io.BufferedReader.readLine(Unknown Source)
[23:47:23] [Thread-6/INFO]: [STDERR]: 	at java.io.BufferedReader.readLine(Unknown Source)
[23:47:23] [Thread-6/INFO]: [STDERR]: 	... 12 more
[23:47:23] [Thread-5/INFO]: [STDERR]: java.io.UncheckedIOException: java.io.EOFException: Unexpected end of ZLIB input stream
[23:47:23] [Thread-5/INFO]: [STDERR]: 	at java.io.BufferedReader$1.hasNext(Unknown Source)
[23:47:23] [Thread-5/INFO]: [STDERR]: 	at java.util.Iterator.forEachRemaining(Unknown Source)
[23:47:23] [Thread-5/INFO]: [STDERR]: 	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
[23:47:23] [Thread-5/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[23:47:23] [Thread-5/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[23:47:23] [Thread-5/INFO]: [STDERR]: 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[23:47:23] [Thread-5/INFO]: [STDERR]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
[23:47:23] [Thread-5/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[23:47:23] [Thread-5/INFO]: [STDERR]: 	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
[23:47:23] [Thread-5/INFO]: [STDERR]: 	at carpet.helpers.StackTraceDeobfuscator.loadSrg(StackTraceDeobfuscator.java:251)
[23:47:23] [Thread-5/INFO]: [STDERR]: 	at carpet.helpers.StackTraceDeobfuscator.lambda$loadMappings$0(StackTraceDeobfuscator.java:178)
[23:47:23] [Thread-5/INFO]: [STDERR]: 	at java.lang.Thread.run(Unknown Source)
[23:47:23] [Thread-5/INFO]: [STDERR]: Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
[23:47:23] [Thread-5/INFO]: [STDERR]: 	at java.util.zip.InflaterInputStream.fill(Unknown Source)
[23:47:23] [Thread-5/INFO]: [STDERR]: 	at java.util.zip.InflaterInputStream.read(Unknown Source)
[23:47:23] [Thread-5/INFO]: [STDERR]: 	at java.util.zip.ZipInputStream.read(Unknown Source)
[23:47:23] [Thread-5/INFO]: [STDERR]: 	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
[23:47:23] [Thread-5/INFO]: [STDERR]: 	at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
[23:47:23] [Thread-5/INFO]: [STDERR]: 	at sun.nio.cs.StreamDecoder.read(Unknown Source)
[23:47:23] [Thread-5/INFO]: [STDERR]: 	at java.io.InputStreamReader.read(Unknown Source)
[23:47:23] [Thread-5/INFO]: [STDERR]: 	at java.io.BufferedReader.fill(Unknown Source)
[23:47:23] [Thread-5/INFO]: [STDERR]: 	at java.io.BufferedReader.readLine(Unknown Source)
[23:47:23] [Thread-5/INFO]: [STDERR]: 	at java.io.BufferedReader.readLine(Unknown Source)
[23:47:23] [Thread-5/INFO]: [STDERR]: 	... 12 more
[23:47:23] [Server thread/INFO]: Loaded 488 advancements
[23:47:23] [Server thread/INFO]: Preparing start region for level 0
</code></pre>
</details>

**Comment by Earthcomputer** [comment]
Looks like the `StackTraceDeobfuscator` is still using HTTP rather than HTTPS to download the MCP mappings, and is getting blocked. Should be switched to HTTPS

**Comment by wegood9** [comment]
But I didn't observe the carpet server trying connecting to minecraftforge.net or making an Internet connection except communications with localhost according to my firewall. Besides, I also could not capture any HTTP traffic sent by javaw using system proxy. And there was no evidence showing that any program had ever sent packets to minecraftforge.net, which was demonstrated by Wireshark.

**Comment by X-com** [comment]
Fixed

**Comment by wegood9** [comment]
I spent some time compiling the latest build, finding the problem still exists.

**Comment by Earthcomputer** [comment]
Try deleting `carpet/joined.srg` and `carpet/methods.csv` and try again

**Comment by wegood9** [comment]
OK, problem solved. Thanks for your generous help!
